on: push
jobs:
  add-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List files
        run: ls -l
      # - name: Add a file
      #   run: |
      #     echo "Hello, world!" > hello.txt
      #     git add hello.txt
      #     git commit -m "Add hello.txt"
      #     git push