on: push
jobs:
  add-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add a file
        run: |
          git config --global user.email "lb@cortilabs.com"
          git config --global user.name "labodk"
          echo "Hello, world!" > hello.txt
          git add hello.txt
          git commit -m "Add hello.txt"
          git push